articles/urls.py
from django.urls import path

from articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.Articles.as_view(), name='articles'),
    path('page/<int:page>/', views.Articles.as_view(), name='pages'),
    path(
        '<slug:category>/<slug:slug>/', views.Article.as_view(), name='article'
    ),
    path('<slug:slug>/', views.Category.as_view(), name='category'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib.sitemaps.views import sitemap

from articles.sitemaps import ArticlesSitemap


sitemaps = {
    'articles': ArticlesSitemap,
}

urlpatterns = [
    path('panel/', admin.site.urls),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += debug_toolbar_urls()

urlpatterns += [
    path('', include('articles.urls'))
]  # без этого "хака" debug toobar не хочет работать о_О

articles/models.py
import shutil
from pathlib import Path

from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django_resized import ResizedImageField
from slugify import slugify


def article_image_path(instance, filename):
    _, ext = filename.rsplit('.', 1)
    name = '.'.join([slugify(instance.title), ext])
    return f'articles/{instance.slug}/{name}'


def category_image_path(instance, filename):
    _, ext = filename.rsplit('.', 1)
    name = '.'.join([slugify(instance.title), ext])
    return f'categories/{instance.slug}/{name}'


class Category(models.Model):
    title = models.CharField('заголовок', max_length=128)
    description = models.CharField('описание', max_length=512, blank=True)
    slug = models.SlugField('URI', max_length=80, unique=True)
    image = ResizedImageField(
        'изображение',
        size=(320, 240),
        upload_to=category_image_path,
        blank=True,
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('articles:category', kwargs={'slug': self.slug})


class Article(models.Model):
    title = models.CharField('заголовок', max_length=128)
    slug = models.SlugField('URI', max_length=80, unique=True)
    description = models.CharField('описание', max_length=512, blank=True)
    content = models.TextField('содержимое')
    image = ResizedImageField(
        'изображение', upload_to=article_image_path, blank=True
    )
    created_at = models.DateTimeField('дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('дата обновления', auto_now_add=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        verbose_name='категория',
        related_name='articles',
    )

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ('-created_at', '-updated_at')
        get_latest_by = ('-updated_at', '-created_at')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy(
            'articles:article',
            kwargs={'category': self.category.slug, 'slug': self.slug},
        )

    def delete(self, **kwargs):
        if self.image:
            path = Path(self.image.path)

            self.image.delete()

            if path.parent.exists():
                shutil.rmtree(path.parent)

        super().delete(**kwargs)

articles/forms.py
from django import forms

from articles import models


class SimpleForm(forms.ModelForm):
    class Meta:
        widgets = {
            'description': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }
        fields = '__all__'


class Category(SimpleForm):
    class Meta(SimpleForm.Meta):
        model = models.Category


class Article(SimpleForm):
    class Meta(SimpleForm.Meta):
        model = models.Article

articles/views.py
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator
from django.views.decorators.http import last_modified
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db.models import Count

from articles import models


def get_article_modified_date(request, **kwargs):
    entry = models.Article.objects.values('updated_at').get(
        slug=kwargs['slug']
    )
    return entry['updated_at']


class Articles(ListView):
    model = models.Article
    template_name = 'articles/index.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'PAGINATE_BY', 2)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['canonical'] = self.request.build_absolute_uri(
            reverse_lazy('articles:articles')
        )

        page_number = context['page_obj'].number
        if page_number == 1:
            context['title'] = self.request.site.name
        else:
            context['title'] = (
                f'Страница {page_number} — {self.request.site.name}'
            )

        return context


# ~ @method_decorator(last_modified(get_article_modified_date), name='dispatch')
class Article(DetailView):
    model = models.Article
    template_name = 'articles/single.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['canonical'] = self.request.build_absolute_uri(
            self.get_object().get_absolute_url()
        )
        return context


class Category(DetailView):
    model = models.Category
    template_name = 'articles/category.html'
    context_object_name = 'category'

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .annotate(articles_count=Count('articles'))
            .filter(articles_count__gt=0)
        )

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = self.object.articles.all()
        return context

templates/articles/category.html
{% extends 'base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block head %}
  {% if category.description %}
    <meta name="description" content="{{ category.description }}">
  {% endif %}
{% endblock %}

{% block body %}

<section class="category">
  <header class="header">
    <h1>{{ category.title }}</h1>
    {% if category.image %}
      <img src="{{ category.image.url }}" alt="{{ category.title }}">
    {% endif %}
  </header>
  <div class="content">{{ category.description }}</div>
</section>
<h2>Статьи в категории:</h2>
<ul>
  {% for article in articles %}
    <li><a href="{{ article.get_absolute_url }}">{{ article }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

templates/articles/index.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block head %}
  <link rel="canonical" href="{{ canonical }}">
{% endblock %}

{% block body %}
{% for article in articles %}

  <article class="article" itemscope itemtype="https://schema.org/Article">
  <header class="header">
    <h2 class="title" itemprop="headline">
      <a href="{{ article.get_absolute_url }}" itemprop="url">{{ article.title }}</a>
    </h2>
  </header>

  {% if article.image %}
    <figure class="thumbnail" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
      <img class="image" width="{{ article.image.width }}" height="{{ article.image.height }}" src="{{ article.image.url }}" alt="{{ article.title }}" itemprop="url">
      <meta itemprop="width" content="{{ article.image.width }}">
      <meta itemprop="height" content="{{ article.image.height }}">
    </figure>
  {% endif %}

  <div class="content" itemprop="description">{{ article.description }}</div>
  <footer class="footer">
    <time class="date" datetime="{{ article.created_at.isoformat }}" itemprop="datePublished">
      {{ article.created_at }}
    </time>
    <a href="{{ article.category.get_absolute_url }}">{{ article.category }}</a>
  </footer>
</article>
{% endfor %}


<aside class="prev-next">
  {% if page_obj.has_previous %}
    <div class="prev">&larr; &laquo;<a title="предыдущая" href="{% if page_obj.previous_page_number == 1 %}{% url 'articles:articles' %}{% else %}{% url 'articles:pages' page=page_obj.previous_page_number %}{% endif %}">предыдущая</a>&raquo;</div>
  {% endif %}

  {% if page_obj.has_next %}
    <div class="next">&laquo;<a title="следующая" href="{% url 'articles:pages' page_obj.next_page_number %}">следующая</a>&raquo; &rarr;</div>
  {% endif %}
</aside>

{% endblock %}

templates/articles/single.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ article.title }}{% endblock %}

{% block head %}
  {% if article.description %}
  <meta name="description" content="{{ article.description }}">
  {% endif %}
  <link rel="stylesheet" href="{% static 'foundation.min.css' %}">
  <link rel="canonical" href="{{ canonical }}">
{% endblock %}

{% block body %}

<article class="article" itemscope itemtype="https://schema.org/Article">
  <header class="header">
    <time class="date" datetime="{{ article.created_at.isoformat }}" itemprop="datePublished">
      {{ article.created_at }}
    </time>
    <h2 class="title" itemprop="headline">{{ article.title }}</h2>
  </header>

  {% if article.image %}
    <figure class="thumbnail" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
      <img class="image" width="{{ article.image.width }}" height="{{ article.image.height }}" src="{{ article.image.url }}" alt="{{ article.title }}" itemprop="url">
      <meta itemprop="width" content="{{ article.image.width }}">
      <meta itemprop="height" content="{{ article.image.height }}">
    </figure>
  {% endif %}

  <div class="content" itemprop="articleBody">{{ article.content|safe }}</div>
  <footer class="footer">
    <div>Рубрика: <a href="{{ article.category.get_absolute_url }}">{{ article.category }}</a></div>
  </footer>
</article>

<aside class="prev-next">
  {% with prev=article.get_previous_by_created_at %}
    {% if prev %}
      <div class="prev">&larr; &laquo;<a title="предыдущая" href="{{ prev.get_absolute_url }}">{{ prev.title }}</a>&raquo;</div>
    {% endif %}
  {% endwith %}

  {% with next=article.get_next_by_created_at %}
    {% if next %}
      <div class="next">&laquo;<a title="следующая" href="{{ next.get_absolute_url }}">{{ next.title }}</a>&raquo; &rarr;</div>
    {% endif %}
  {% endwith %}
</aside>
{% endblock %}

{% block scripts %}
<script src="{% static 'highlight.min.js' %}"></script>
<script>hljs.highlightAll();</script>
{% endblock %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar">
      <a href="/mariadb/">MariaDB</a>
      <a href="/postgresql/">PostgreSQL</a>
      <a href="/basics/">Основы</a>
    </nav>
    <header class="site-header">
      <h1 class="title"><a href="{% url 'articles:articles' %}">{{ request.site.name }}</a></h1>
    </header>
    <div class="site-body">{% block body %}{% endblock %}</div>
    <footer class="site-footer"></footer>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/tg_message.html
«<a href="https://{{ site }}{{ article.get_absolute_url }}">{{ article.title }}</a>»

{{ article.description }}